# Generated by Django 3.0 on 2021-02-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_stock_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeestockkeymap',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Not Issued', 'Not Issued'), ('With User', 'With User')], max_length=10),
        ),
    ]
