# Generated by Django 3.0 on 2021-02-04 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210204_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestockkeymap',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 4, 11, 44, 31, 671877, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeestockkeymap',
            name='issued_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
